# Cloudflare Pages configuration
name = "3dportfolio"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Build settings
[build]
command = "CI=false npm run build"
output_dir = "dist"
base_dir = ""

# Environment variables
[env.production]
NODE_VERSION = "20"
CI = "false"

[env.preview]
NODE_VERSION = "20"
CI = "false"

# Build processing
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.static_files]
cache_max_age = "1y"

# MIME types - Updated to ensure proper JavaScript module handling
[build.processing.headers]
for = ["/assets/*.js", "/*.js", "/**/*.js"]
[build.processing.headers.values]
Content-Type = "application/javascript"

[[build.processing.headers]]
for = ["/**/*.mjs"]
[build.processing.headers.values]
Content-Type = "application/javascript"

[[build.processing.headers]]
for = ["/**/*.ts", "/**/*.tsx", "/**/*.jsx"]
[build.processing.headers.values]
Content-Type = "application/javascript"

# Page Rules
[[routes]]
pattern = "/*"
script = ""

# SPA fallback
[[routes]]
pattern = "/*"
handler = "filesystem"

[[routes]]
pattern = "/*"
fallback_redirect = "/"